# Generated by Django 5.2 on 2025-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0003_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTrainingSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.IntegerField()),
                ('slot_number', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourtTimePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(choices=[('Александр Игнатов', 'Саша'), ('Анастасия Бунарева', 'Настя')])),
                ('start_datetime', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='court_number',
            new_name='court_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
