# Generated by Django 5.2 on 2025-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0004_alltrainingslots_courttimeprice_trainings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainings',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='trainings',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='trainings',
            name='level',
            field=models.CharField(choices=[('light', 'Начальный'), ('medium', 'Уверенный'), ('hard', 'Продвинутый')], default='light'),
        ),
        migrations.AddField(
            model_name='trainings',
            name='time',
            field=models.TimeField(choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='00:00'),
        ),
    ]
