# Generated by Django 5.2 on 2025-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0005_remove_trainings_start_datetime_trainings_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='time',
            field=models.CharField(choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='00:00'),
        ),
    ]
