# Generated by Django 5.2 on 2025-05-26 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0006_alter_trainings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
