# Generated by Django 5.2 on 2025-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0008_alter_courttimeprice_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttimeprice',
            name='time',
            field=models.CharField(choices=[('6:00', '6:00'), ('8:00', '8:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00'), ('20:00', '20:00'), ('22:00', '22:00')], default='00:00'),
        ),
    ]
