# Generated by Django 5.2 on 2025-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0009_alter_courttimeprice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttimeprice',
            name='week_day',
            field=models.IntegerField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')]),
        ),
    ]
