# Generated by Django 5.2 on 2025-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0010_alter_courttimeprice_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttimeprice',
            name='week_day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')]),
        ),
    ]
