# Generated by Django 5.2 on 2025-05-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_app', '0011_alter_courttimeprice_week_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookind_datetime',
            new_name='booking_datetime',
        ),
    ]
